If not in any repo, skip the file ownership test

diff --git a/bin/start-docker-ssh-exec b/bin/start-docker-ssh-exec
--- a/bin/start-docker-ssh-exec
+++ b/bin/start-docker-ssh-exec
@@ -2,16 +2,15 @@
 
 # Verify we're the owner of all files in this repo
 git_top_level="$(git rev-parse --show-toplevel 2> /dev/null)"
-if [ "$git_top_level" == "" ]; then
-  echo "Error: Not in a git repo"
-  exit 1
-fi
-WHOAMI="$(whoami)"
-if [[ $(find $git_top_level -nouser -or -not -user $WHOAMI) ]]; then
-  echo "Error: There are files in this repo that are not owned by $WHOAMI. This can"
-  echo "cause docker-sync to behave badly, so you'll want to re-chown your files."
-  echo "You can find those files with: find $git_top_level -nouser -or -not -user $WHOAMI"
-  exit 1
+if [ "$git_top_level" != "" ]; then
+  whoami="$(whoami)"
+  if [[ $(find $git_top_level -nouser -or -not -user $whoami) ]]; then
+    echo "Error: You're in a repo with files that are not owned by $whoami. This can"
+    echo "cause docker-sync to behave badly, so you'll almost certainly want to"
+    echo "re-chown your files. You can find those files with:"
+    echo "find $git_top_level -nouser -or -not -user $whoami"
+    exit 1
+  fi
 fi
 
 # Start the docker-ssh-container if not already started
