Error out if specified ssh key file is missing

diff --git a/bin/start-docker-ssh-exec b/bin/start-docker-ssh-exec
--- a/bin/start-docker-ssh-exec
+++ b/bin/start-docker-ssh-exec
@@ -1,6 +1,10 @@
 #!/bin/bash
 
 key_path=${1:-"$HOME/.ssh/id_rsa"}
+if [ ! -f $key_path ]; then
+  echo "Error: no ssh key file found at '$key_path'"
+  exit 1
+fi
 
 echo "
 This script will install a docker-ssh-exec server container.
